name: Update CF Nodes

on:
  schedule:
    - cron: '*/18 * * * *'
  workflow_dispatch:


permissions:
  contents: write


jobs:

  update:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v5


      - name: Install dependencies
        run: |
          pip install requests


      - name: Generate nodes
        run: |
          python3 update.py


      - name: Commit
        run: |

          git config --global user.name "github-actions"

          git config --global user.email "github-actions@github.com"


          git add .


          git commit -m "update" || exit 0


          git push
